input {
  beats {
    port => 5044 #logstash listen on port 5044
  }
}

filter {
  # parse json logs from the app
  if [message] =~ /^\{/ {
    json {
      source => "message"
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "node-api-%{+YYYY.MM.dd}"
  }
}
