#Promethus self managed..
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: node-api-alerts
  namespace: production
spec:
  groups:
    - name: node-api
      rules:
        # alert if error rate goes above 5%
        - alert: HighErrorRate
          expr: |
            sum(rate(http_requests_total{job="node-api", status=~"5.."}[5m]))
            /
            sum(rate(http_requests_total{job="node-api"}[5m])) > 0.05
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "too many errors on node-api"

        # alert if response time is slow
        - alert: HighLatency
          expr: |
            histogram_quantile(0.95,
              sum(rate(http_request_duration_seconds_bucket{job="node-api"}[5m]))
              by (le)
            ) > 1
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "node-api responding slowly"
